# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt ./
# Remove asyncio requirement if present
RUN sed -i '/asyncio/d' requirements.txt && pip install --no-cache-dir -r requirements.txt

COPY . ./

CMD ["python", "main.py"]
